import "./globals.css";
import Navbar from "./_comonents/Navbar/Navbar";
import Background from "./_comonents/Background/Background";
import { Merriweather } from 'next/font/google';

const merriweather = Merriweather({
  variable: "--font-merriweather",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata = {
  title: "karim",
  description: "Generated by create next app",
  icons: {
    icon: "Icon/favicon.svg",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${merriweather.variable} antialiased bg-zinc-900`}
      >
        <Background>
          <Navbar />
          {children}
        </Background>
      </body>
    </html>
  );
}
